const enum COLOR_PALETTE {
  LEETECHO_BLUE = '#2688f0',
  LEETECHO_BLACK = '#0d0d0d',
  LEETECHO_WHITE = '#fffffe',
  LEETECHO_LIGHT_BLUE = '#56a2f3',
  LEETECHO_DARK_BLUE = '0f6fd4',
  LEETECHO_LIGHT_BLACK = '#262626',
  LEETECHO_GREY = '#F8F8FA',
}

export { COLOR_PALETTE };