const enum COLOR_PALETTE {
  LEETECHO_BLUE = '#2688f0',
  LEETECHO_BLACK = '#0d0d0d',
  LEETECHO_WHITE = '#fffffe',
  LEETECHO_LIGHT_BLUE = '#56a2f3',
  LEETECHO_DARK_BLUE = '#0f6fd4',
  LEETECHO_LIGHT_BLACK = '#262626',
  LEETECHO_GREY = '#F8F8FA',
  LEETECHO_INPUT_BACKGROUND = '#E5E8EA',
  LEETECHO_INPUT_PLACEHOLDER_COLOR = '#6E7174',
  LEETECHO_INPUT_HOVER_BORDER_BG = '#C6CACD',
}

export { COLOR_PALETTE };