const enum COLOR_PALETTE {
  LEETECHO_BLUE = '#2688f0',
  LEETECHO_BLACK = '#0d0d0d',
  LEETECHO_WHITE = '#fffffe',
  LEETECHO_LIGHT_BLUE = '#56a2f3',
  LEETECHO_DARK_BLUE = '#0f6fd4',
  LEETECHO_LIGHT_BLACK = '#262626',
  LEETECHO_GREY = '#F8F8FA',

  LEETECHO_RED = '#f5222d',
  LEETECHO_GREEN = '#3CB346',
  LEETECHO_YELLOW = '#FC8801',

  /** Input */
  LEETECHO_INPUT_BACKGROUND = '#F4F5F5',
  LEETECHO_INPUT_PLACEHOLDER_COLOR = '#6E7174',
  LEETECHO_INPUT_HOVER_BG = '#ECECED',

  /** Header searchTool */
  LEETECHO_HEADER_SEARCH_BG = '#E5E8EA',
  LEETECHO_HEADER_SEARCH_BG_HOVER = '#C6CACD',
}

export { COLOR_PALETTE };
